package Model;

import java.time.LocalDateTime;

/**
 *This class represents the information about the race.
 *
 * @author Denis Jorge Gandarillas Delgado
 */

public class Race {

    private double cost;
    private String nameDriver, nameClient, startingPoint, arrivalPoint;
    private int passengerCount;
    private LocalDateTime dateTime;

    /**
     * This is the constructor method of the <i style="color:red">Race</i> class.
     *
     * <p>
     *     The cost of the ticket will be generated by a random number.
     *     The date and time of the order will be obtained through the <i style="color:red">LocalDateTime()</i> function.
     * </p>
     *
     * @param nameDriver Name of the assigned driver.
     * @param nameClient Name of the client who requested the service.
     * @param startingPoint Location of the starting point where the cab picks up the client.
     * @param arrivalPoint Location of the arrival point where the cab drops off the client.
     * @param passengerCount The number of passengers entering the cab.
     */

    public Race(String nameDriver, String nameClient, String startingPoint, String arrivalPoint, int passengerCount) {
        this.cost = Math.random()*(50-20)*20;
        this.nameDriver = nameDriver;
        this.nameClient = nameClient;
        this.startingPoint = startingPoint;
        this.arrivalPoint = arrivalPoint;
        this.passengerCount = passengerCount;
        dateTime = LocalDateTime.now();
    }

    /**
     * This method returns the value of the variable cost.
     *
     * @return cost
     */

    public double getCost() {
        return cost;
    }

    /**
     * This method helps to set a value on the cost variable.
     *
     * @param cost Cost of the race.
     */

    public void setCost(double cost) {
        this.cost = cost;
    }

    /**
     * This method returns the value of the variable nameDriver.
     *
     * @return nameDriver
     */

    public String getNameDriver() {
        return nameDriver;
    }

    /**
     * This method helps to set a value on the nameDriver variable.
     *
     * @param nameDriver Name of the assigned driver.
     */

    public void setNameDriver(String nameDriver) {
        this.nameDriver = nameDriver;
    }

    /**
     * This method returns the value of the variable nameClient.
     *
     * @return nameClient
     */

    public String getNameClient() {
        return nameClient;
    }

    /**
     * This method helps to set a value on the nameClient variable.
     *
     * @param nameClient Name of the client who requested the service.
     */

    public void setNameClient(String nameClient) {
        this.nameClient = nameClient;
    }

    /**
     * This method returns the value of the variable startingPoint.
     *
     * @return startingPoint
     */

    public String getStartingPoint() {
        return startingPoint;
    }

    /**
     * This method helps to set a value on the startingPoint variable.
     *
     * @param startingPoint Location of the starting point where the cab picks up the client.
     */

    public void setStartingPoint(String startingPoint) {
        this.startingPoint = startingPoint;
    }

    /**
     * This method returns the value of the variable arrivalPoint.
     *
     * @return arrivalPoint
     */

    public String getArrivalPoint() {
        return arrivalPoint;
    }

    /**
     * This method helps to set a value on the arrivalPoint variable.
     *
     * @param arrivalPoint Location of the arrival point where the cab drops off the client.
     */

    public void setArrivalPoint(String arrivalPoint) {
        this.arrivalPoint = arrivalPoint;
    }

    /**
     * This method returns the value of the variable passengerCount.
     *
     * @return passengerCount
     */

    public int getPassengerCount() {
        return passengerCount;
    }

    /**
     * This method helps to set a value on the passengerCount variable.
     *
     * @param passengerCount The number of passengers entering the cab.
     */

    public void setPassengerCount(int passengerCount) {
        this.passengerCount = passengerCount;
    }

    /**
     * This method returns the value of the variable dateTime.
     *
     * @return dateTime
     */

    public LocalDateTime getDateTime() {
        return dateTime;
    }

    /**
     * This method helps to set a value on the dateTime variable.
     * @param dateTime The date and time of the cab order.
     */

    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }
}