package Model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *This class represents the information about the race.
 *
 * @author Denis Jorge Gandarillas Delgado
 */

public class Race {

    private double cost;
    private String nameDriver, nameClient, startingPoint, arrivalPoint, currency;
    private int passengerCount;
    private String dateTime;

    /**
     * This is the constructor method of the <i style="color:red">Race</i> class.
     *
     * <p>
     *     The cost of the ticket will be generated by a random number.
     *     The date and time of the order will be obtained through the <i style="color:red">LocalDateTime()</i> function.
     *     nameDriver Name of the assigned driver.
     *     nameClient Name of the client who requested the service.
     *     startingPoint Location of the starting point where the cab picks up the client.
     *     arrivalPoint Location of the arrival point where the cab drops off the client.
     *     passengerCount The number of passengers entering the cab.
     * </p>
     */

    public Race() {
        this.nameClient = null;
        this.nameDriver = null;
        this.cost = 0;
        this.startingPoint = null;
        this.arrivalPoint = null;
        this.passengerCount = 0;
        this.dateTime = "";
        this.currency = "BOB";
    }

    /**
     * This method returns the value of the variable cost.
     *
     * @return cost
     */

    public double getCost() {
        return cost;
    }

    /**
     * This method helps to set a value on the cost variable.
     * Generated randomly because for the moment, we do not calculate the trip cost in base of the distance.
     */

    public void setCost() {
        this.cost = Math.random()*(50-20+1)+20;
    }

    /**
     * This method returns the value of the variable nameDriver.
     *
     * @return nameDriver
     */

    public String getNameDriver() {
        return nameDriver;
    }

    /**
     * This method helps to set a value on the nameDriver variable.
     *
     * @param nameDriver Name of the assigned driver.
     */

    public void setNameDriver(String nameDriver) {
        this.nameDriver = nameDriver;
    }

    /**
     * This method returns the value of the variable nameClient.
     *
     * @return nameClient
     */

    public String getNameClient() {
        return nameClient;
    }

    /**
     * This method helps to set a value on the nameClient variable.
     *
     * @param nameClient Name of the client who requested the service.
     */

    public void setNameClient(String nameClient) {
        this.nameClient = nameClient;
    }

    /**
     * This method returns the value of the variable startingPoint.
     *
     * @return startingPoint
     */

    public String getStartingPoint() {
        return startingPoint;
    }

    /**
     * This method helps to set a value on the startingPoint variable.
     *
     * @param startingPoint Location of the starting point where the cab picks up the client.
     */

    public void setStartingPoint(String startingPoint) {
        this.startingPoint = startingPoint;
    }

    /**
     * This method returns the value of the variable arrivalPoint.
     *
     * @return arrivalPoint
     */

    public String getArrivalPoint() {
        return arrivalPoint;
    }

    /**
     * This method helps to set a value on the arrivalPoint variable.
     *
     * @param arrivalPoint Location of the arrival point where the cab drops off the client.
     */

    public void setArrivalPoint(String arrivalPoint) {
        this.arrivalPoint = arrivalPoint;
    }

    /**
     * This method returns the value of the variable passengerCount.
     *
     * @return passengerCount
     */

    public int getPassengerCount() {
        return passengerCount;
    }

    /**
     * This method helps to set a value on the passengerCount variable.
     *
     * @param passengerCount The number of passengers entering the cab.
     */

    public void setPassengerCount(int passengerCount) {
        this.passengerCount = passengerCount;
    }

    /**
     * This method returns the value of the variable dateTime.
     *
     * @return dateTime
     */

    public String getDateTime() {
        return dateTime;
    }

    public String getCurrency() {
        return currency;
    }

    /**
     * This method helps to set a value on the dateTime variable.
     */

    public void setDateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
        this.dateTime = formatter.format(LocalDateTime.now());
    }
}